export const AUTH_START = 'AUTH_START';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL'; 
export const AUTH_LOGOUT = 'AUTH_LOGOUT'